### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by ORCA666** [jungjin0003/GlobalWinHook#1]
this is the same issue as https://github.com/jungjin0003/WinHook/issues/1
 
hii again, and thank you for uploading your work, this is basically not an issue but i wanted to ask the same question, and i think since you uploaded 2 hooking respiratories that you some how nailed it.
i am not asking for the source code of how to hook createProcess and openprocess but i am asking how to use your code, i am not that good when it goes to api. 

thank you very much and i hope you have a nice day

**Comment by jungjin0003** [comment]
WinHook and GlobalWinHook are different things. WinHook is a library that hooks functions of a single process, and GlobalWinHook is a library in which the child process is also hooked when the hooked process creates a child process.

**Comment by alexa872** [comment]
> WinHook and GlobalWinHook are different things. WinHook is a library that hooks functions of a single process, and GlobalWinHook is a library in which the child process is also hooked when the hooked process creates a child process.

look mate, the main reason why i am doing this is that because i want to hook  createProcess and openProcess, why? because i am building a malware and i want to hook these functions to bypass the run time check of windows defender, 
i got this idea from https://labs.f-secure.com/blog/bypassing-windows-defender-runtime-scanning/
now if you give me a hand in this we might share some experience and if you want to read about it it is  over here 

https://github.com/alexa872/EVA-fully-undetectable

i tested a lot of evasion tech, some of them worked but the run time check always fk me up, so can you give me a tip on how to hook these functions, using your code, cz labs.f-secure way does not work.

i really appreciate your time

**Comment by alexa872** [comment]
> WinHook and GlobalWinHook are different things. WinHook is a library that hooks functions of a single process, and GlobalWinHook is a library in which the child process is also hooked when the hooked process creates a child process.

the problem is that i dont have know how win defender works , i mean how it launches its scans and when it triggers its api functions, so idk how to hook these functions, we might use GlobalWinHook  to hook msmpeng.exe process aka windows defender. so what do you think ?

**Comment by alexa872** [comment]
look man, i got a big idea i really want your help, some real shit is about to be built, trust me it is something crazy
please just mail me at zakazeke8@gmail.com or post your e-mail, you will like the idea !
